services:
  highcharts-export-server:
    # Because Chrome does not support ARM on Linux, we need to specify the platform to linux/amd64
    platform: linux/amd64
    build:
      context: .
      target: dev
    restart: always
    environment:
      - EXPORT_RASTERIZATION_TIMEOUT=20000
    healthcheck:
      test: wget -qO- http://localhost:8080/health
      interval: 20s
      timeout: 4s
      retries: 3
